version: "3"

services:
  rng:
    build: rng
    image: hopla/dockercoins_rng:${TAG}
    deploy:
      mode: global

  hasher:
    build: hasher
    image: hopla/dockercoins_hasher:${TAG}

  webui:
    build: webui
    image: hopla/dockercoins_webui:${TAG}
    ports:
    - "8000:80"

  redis:
    image: redis

  worker:
    build: worker
    image: hopla/dockercoins_worker:${TAG}
    deploy:
      replicas: 10

